### ISSUE TITLE
Remove Node_modules

### ISSUE THREAD

**Issue by pragmaticAweds** [miskiat/TYPESCRIPTT#1]
Remove node_modules from your code and structure your readme content very well.

**Comment by pragmaticAweds** [comment]
![Screenshot_2023-02-21-23-47-51-728_com android chrome-edit](https://user-images.githubusercontent.com/70960505/220476423-07e5814b-6f21-42ca-be25-4ea42dcbbcde.jpg)

**Comment by pragmaticAweds** [comment]
No subject for your readme file

**Comment by pragmaticAweds** [comment]
![Screenshot_2023-02-21-23-47-30-111_com android chrome-edit](https://user-images.githubusercontent.com/70960505/220476505-c652e591-c86b-46b5-985e-f94a4d4db7a1.jpg)

Node_modulew still exist

**Comment by miskiat** [comment]
Done.....Kindly forward the project you used as readme example.
